app:
    resource: '@AppBundle/Controller/Defaultcontroller.php'
    type: annotation

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

users:
    type:     rest
    resource: AppBundle\Controller\UserController
