app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

customers:
    type:     rest
    resource: AppBundle\Controller\IOT\CustomerController
    prefix: /api

devices:
    type:     rest
    resource: AppBundle\Controller\IOT\DeviceController
    prefix: /api

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController
    prefix: /api

users:
    type:     rest
    resource: AppBundle\Controller\UserController
    prefix: /api

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController
    prefix: /api

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController
    prefix: /api

app.swagger_ui:
    path: /documentation
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
