# Data
AppBundle\Entity\IOT\Data:
    properties:
        temperature:
            - NotBlank: ~
            - Type: float
        humidity:
            - NotBlank: ~
            - Type: float

# Device
AppBundle\Entity\IOT\Device:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        description:
            - NotBlank: ~
            - Type: string

# Customer
AppBundle\Entity\IOT\Customer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        name:
            - NotBlank: ~
            - Type: string
        description:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        address:
            - NotBlank: ~
            - Type: string
        city:
            - NotBlank: ~
            - Type: string
        state:
            - NotBlank: ~
            - Type: string
        postalcode:
            - NotBlank: ~
            - Type: string
        devices:
            - Valid: ~

# Place
AppBundle\Entity\Place:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        address:
            - NotBlank: ~
            - Type: string
        prices:
            - Valid: ~

# User
AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50

# Price
AppBundle\Entity\Price:
    properties:
        type:
            - NotNull: ~
            - Choice:
                choices: [less_than_12, for_all]
        value:
            - NotNull: ~
            - Type: numeric
            - GreaterThanOrEqual:
                value: 0

# Credentials
AppBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank: ~
            - Type: string
        password:
            - NotBlank: ~
            - Type: string

