AppBundle\Entity\IOT\Customer:
    exclusion_policy: none
    properties:
        id:
            groups: ['customer', 'device']
        name:
            groups: ['customer', 'device']
        description:
            groups: ['customer', 'device']
        email:
            groups: ['customer', 'device']
        city:
            groups: ['customer', 'device']
        state:
            groups: ['customer', 'device']
        postalcode:
            groups: ['customer', 'device']
        address:
            groups: ['customer', 'device']
        devices:
            groups: ['customer']