AppBundle\Entity\IOT\Device:
    exclusion_policy: none
    properties:
        id:
            groups: ['customer', 'device']
        name:
            groups: ['customer', 'device']
        description:
            groups: ['customer', 'device']
        customer:
            groups: ['device']