AppBundle\Entity\IOT\Customer:
    exclusion_policy: none
    properties:
        id:
            groups: ['customer']
        name:
            groups: ['customer']
        description:
            groups: ['customer']
        email:
            groups: ['customer']
        city:
            groups: ['customer']
        state:
            groups: ['customer']
        postalcode:
            groups: ['customer']
        address:
            groups: ['customer']
